### ISSUE TITLE
Unstable Rift Shard texture went poof again. 

### ISSUE THREAD

**Issue by DragonKiwi19** [pick1t/CIvBlock#4]
See description. They're invis again.

**Comment by pick1t** [comment]
Known issue, will be fixed next patch as per Pre-Patch notes on Discord

**Comment by pick1t** [comment]
This issue should be fixed now. Leaving this open pending seeing if it actually is.

**Comment by pick1t** [comment]
This has been hotfixed and should not happen again, unless client side shaders ignore the texture.
